### ISSUE TITLE
T1M bug? Camera ignoring doors?

### ISSUE THREAD

**Issue by annlyt** [rr-/Tomb1Main#204] opened 2021-11-09 10:07 UTC
I don't know if this issue has been posted already, but I noticed the camera seems to ignore doors. So it can move to the other side of a door instead of acting like a wall for the camera.

It's most noticeable at the beginning of St Francis Folly where the initial camera position is on the other side of the door instead of at Lara's side.

**Comment by rr-** [comment] 2021-11-09 10:24
Does it happen only with custom WSAD camera or with normal camera as well? If the former, it's a T1M bug, if the latter, it's an OG bug.

**Comment by annlyt** [comment] 2021-11-09 10:28
Both. It was happening before the manual camera was added.

**Comment by rr-** [comment] 2021-11-09 10:29
And does it happen with TombATI.exe?

**Comment by annlyt** [comment] 2021-11-09 10:29
But wasn't happening on TombATI. There was a different bug in that case.

**Comment by annlyt** [comment] 2021-11-09 10:30
In TombATI it started too zoomed in.

**Comment by Richard-L** [comment] 2021-11-09 20:40
Can't reproduce this @annlyt. What's wrong?

https://user-images.githubusercontent.com/4934209/141000951-95060c55-c4e8-433a-b5ca-3532b723b374.mp4

**Comment by thatguyfrombb** [comment] 2021-11-11 21:25
@annlyt Can't reproduce the bug here either. Any chance you're not running stock T1M v1.3.0?

**Comment by annlyt** [comment] 2021-11-11 22:25
OK, it seems it might have already been fixed.

**Comment by rr-** [comment] 2021-11-16 22:25
Is it OK to close it?

**Comment by rr-** [comment] 2021-11-16 22:39
From Discord:

>TRFan94: It's OK to close the camera ignoring doors issue @rr-.
>
>Sorry, can't be bothered to go to Github rn.

**Closed by rr-** 2021-11-16 22:39 UTC
