### ISSUE TITLE
TR1M bug: No black background on main menu after end of manor level

### ISSUE THREAD

**Issue by atombraiderfan** [rr-/Tomb1Main#288] opened 2021-12-28 07:26 UTC
Hi, hope everyone have had a good Christmas!

Just to report a bug I've encountered, when Lara climbs out of the swimming pool and the manor level ends, this is what the main menu looks like:

![screenshot0001](https://user-images.githubusercontent.com/94776985/147538957-8a039200-81b3-4382-894c-c01133697a35.jpg)

This happens on TR1M version 2.1

**Comment by Richard-L** [comment] 2021-12-28 08:52
Ah yeah we'd talked about that. Was introduced with the fan-made backdrops that span the full screen and thus cover this up.

**Comment by walkawayy** [comment] 2022-01-04 04:18
I can't reproduce this? Does it depend on resolution?

**Comment by atombraiderfan** [comment] 2022-01-04 08:01
> I can't reproduce this. Does it only happen on certain resolutions?

The resolution I'm using is 1920x1080 (16:9)

**Comment by rr-** [comment] 2022-01-04 09:28
I provided a fix that I am not sure if it is going to work. @atombraiderfan could you please see if it resolves the issue you're experiencing?

[Tomb1Main-2.1-8-ga5dd7d0.zip](https://github.com/rr-/Tomb1Main/files/7806636/Tomb1Main-2.1-8-ga5dd7d0.zip)

**Comment by atombraiderfan** [comment] 2022-01-04 09:47
> I provided a fix that I am not sure if it is going to work. @atombraiderfan could you please see if it resolves the issue you're experiencing?
> 
> [Tomb1Main-2.1-8-ga5dd7d0.zip](https://github.com/rr-/Tomb1Main/files/7806636/Tomb1Main-2.1-8-ga5dd7d0.zip)

That did the trick, thank you rr-! 👍 🥇  

I've tested it on three occasions to make sure it works.  The screenshot below is after the manor level ends.

![screenshot0002](https://user-images.githubusercontent.com/94776985/148040071-07e3532c-e397-4c83-bf02-479359380f16.jpg)

**Comment by rr-** [comment] 2022-01-04 09:55
Thanks, we'll include the fix in 2.2 which will be released some time this week :)

**Closed** 2022-01-04 15:18 UTC
Labels: T1M bug
