### ISSUE TITLE
Underwater currents sometimes stop working

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#127] opened 2021-10-15 20:20 UTC
When you start the level and fall into the stream, it sucks you down the waterfall as is expected. After you've picked up the three cogs in the level and make your way back to put them in, this happened:

TombATI:

https://user-images.githubusercontent.com/4934209/137548483-d09b6e1b-6e82-4d6e-8d83-ac0a3a5f127d.mp4

TR1Main:

https://user-images.githubusercontent.com/4934209/137548586-585ea41d-9256-4480-9f4c-4352a2d18885.mp4

Tested the full scenario of selecting the cogs in both games and then falling into the stream. If the cogs are actually related or not I don't know of course. In TR1Main, if you save whilst you're swimming in the non-working stream, and load, it'll suddenly suck you down again, as if it was reset.

**Comment by rr-** [comment] 2021-10-15 20:32
Points of interest: 

- LaraWaterCurrent
- CalculateTarget
- UpdateLOT
- TestTriggers, TO_SINK switch

**Comment by walkawayy** [comment] 2022-01-08 21:13
Left bad, right good. Only difference seems to be the tail value getting set in the good save (line 13). Head is loaded from the save, but it gets to 255 quickly in both saves, so that doesn't seem to matter. 

![image](https://user-images.githubusercontent.com/81546780/148660139-3d6dc24f-c24b-473f-a4a6-19b3a9d5c163.png)

Is there any harm in just clearing the LOT values if Lara is out of water? The only time they are used for Lara is for the current. I think that would fix this issue. Though I still don't fully understand how they were badly saved.

**Comment by walkawayy** [comment] 2022-01-19 22:17
Here. The thing is, we don't know if @Richard-L did any weird fly cheat stuff to mess up the save and no one else could reproduce the problem.

@asasas9500 aka ChocolateFan was going to take a look at it now that they can build T1M. But idk if they started debugging yet.

[broken-current-save.zip](https://github.com/rr-/Tomb1Main/files/7900886/broken-current-save.zip)

**Comment by rr-** [comment] 2022-02-09 01:42
Has anyone in the world been able to reproduce this? If not I'd suggest closing this and reopen when there are more reports.

**Comment by Richard-L** [comment] 2022-02-09 08:00
I would agree. Let's close this.

**Comment by Rapora9** [comment] 2022-02-09 11:08
Can I comment on an issue that is closed? I just wanted to say that sometimes, after using the fly cheat, currents stop working for me. This does not happen every time. Should I try to investigate more?

**Comment by rr-** [comment] 2022-02-09 11:13
>Should I try to investigate more?

Yes please.

**Comment by Rapora9** [comment] 2022-02-09 12:39
I managed to break the current both in Lost Valley and my custom level. They seem to work in a slightly different logic though so next I will try to find out how to make this consistent.

**Comment by Rapora9** [comment] 2022-02-09 19:29
Using fly cheat is not necessary to produce this bug so it's more "severe" since it could happen even with a normal, non-cheating gameplay. Here is a clip where I've played with cheats disabled from the start of a new game to Lost Valley. The current breaks as easily as jumping into the water and saving & loading at the moment of impact. The square I jump to may be relevant because it doesn't always work.

https://user-images.githubusercontent.com/97730054/153275813-e1f1562d-cfcd-458f-a700-b5733138f535.mp4

**Comment by Richard-L** [comment] 2022-02-09 20:22
Interesting. After seeing this, what I do notice from my initial videos is that the state loaded has Lara positioned over water (too), as I saved in the moment she started climbing up. So perhaps loading from a state where Lara is on a tile with water on it has to do with it?

**Comment by Rapora9** [comment] 2022-02-10 22:27
Is it okay if I write this many comments...?

I mentioned this earlier but going to put it here with my own video too. In Sanctuary of the Scion, if you save&load right after using the underwater switch that is under a big statue, the current stops working: 
https://user-images.githubusercontent.com/97730054/153506799-efbdb827-e5e7-409d-a5b1-86c4ce26fd8b.mp4

Despite my best efforst, I have not been able to stop the current(s) from working in St. Francis Folly, Colosseum, Palace Midas and Tomb of Tihocan.

Should this issue be renamed since it's not only the Lost Valley current that is not working, and it's also not limited to t1m since it happens in tombati too?

**Comment by Rapora9** [comment] 2022-02-20 10:56
[level1&2.zip](https://github.com/rr-/Tomb1Main/files/8103795/level1.2.zip)
Here is 2 test levels: LEVEL1 and LEVEL2. The geometry of the levels is following:

![Näyttökuva (310)](https://user-images.githubusercontent.com/97730054/154838976-50312405-8b44-4bfd-8090-bb6a0560e5f3.png)

There are only 2 rooms: upper room and water room (which has a wall sector in the middle). In the water room, there are 2 sinks and 2 rows of triggers to create the current. In LEVEL1 the sinks are mixed so that they are located behind the wall when compared to their triggers. A picture for clarity:

![Näyttökuva (310)](https://user-images.githubusercontent.com/97730054/154839052-72194d6d-9c58-4229-b7df-c2a75407deb3.png)

In LEVEL2 they are placed normally (sinks are next to their respective triggers).

### Test results

- LEVEL2: I cannot make the currents to break at all
- LEVEL1: whichever current Lara enters first, works. The other current does not work. If I jump to current1, it works and the current2 doesn't work. If I first jump to current2, it works and the current1 doesn't. No need to save or load to make this happen (except when you want to try again and start a new game / load a save where you haven't entered the water yet).

Now, pathfinding in Tomb Editor is not 1:1 to Tomb Raider 1. For example gorillas sadly cannot climb. So these results should be taken with a grain of salt. Still this might help to figure out why the current would stop working.

**Comment by walkawayy** [comment] 2022-07-27 00:03
Potentially fixed in this build. Trying to clear Lara's LOT values when the current goes inactive.

[T1M Current Fix v1.zip](https://github.com/rr-/Tomb1Main/files/9193964/T1M.Current.Fix.v1.zip)

**Closed** 2022-08-19 21:04 UTC
Labels: OG bug
