### ISSUE TITLE
resolution setting affecting things that aren't the resolution

### ISSUE THREAD

**Issue by staticanimal** [rr-/Tomb1Main#346] opened 2022-01-17 13:01 UTC
changing the resolution does not affect the game's rendering resolution as it should but instead just changes its aspect ratio to that of the resolution which was set (e.g. 1280x720 will set it to 16:9, 640x480 will set it to 4:3 and 320x200 (using the resolution override in Tomb1Main.json5) will set it to 16:10)

additionally, changing the resolution affects the strength of the polygon jitter effect used to emulate water distortion. lower resolutions make the effect stronger and more noticeable, higher resolutions make it less intensive. an example of this can be seen [here](https://video.twimg.com/ext_tw_video/1483059391729479683/pu/vid/1280x720/PJ80vh4gTY8ESblA.mp4)

**Comment by rr-** [comment] 2022-01-17 14:05
Duplicate of #114

**Closed by rr-** 2022-01-17 14:05 UTC
