### ISSUE TITLE
Feature request: Restart level after dying

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#200] opened 2021-11-08 23:48 UTC
Other than to load a state, should the passport's "restart level" page also be available upon dying, like it is in the console versions? 

Related: #48

**Comment by walkawayy** [comment] 2021-11-08 23:52
I'm not sure what you're saying. The goal is to make restart level an option on death like it is in TR2Main. It's not available anywhere else on the current WIP code.

**Comment by Richard-L** [comment] 2021-11-09 00:39
That's pretty much what I'm saying.

**Comment by walkawayy** [comment] 2021-11-09 00:40
So is this a duplicate of #48 then?

**Comment by rr-** [comment] 2021-11-09 08:36
That's the same thing in my opinion.

**Closed** 2021-11-09 09:47 UTC
