### ISSUE TITLE
T1M bug: 3D Pick-ups sometimes too dark

### ISSUE THREAD

**Issue by Richard-L** [rr-/Tomb1Main#206] opened 2021-11-09 22:39 UTC
Although they look really nice, sometimes they can be unexpectedly dark.

![image](https://user-images.githubusercontent.com/4934209/141016754-dfb1dc8f-2d94-48f4-ad37-582745648d9e.png)

Perhaps is it worth considering to tinker with their lighting?

**Comment by rr-** [comment] 2021-11-09 22:40
@oziphantom

**Comment by Richard-L** [comment] 2021-11-10 13:20
Also just to say I understand better now why the sizing consideration was brought up on Discord. You kind of go in cycles of thinking they're too small and thinking they're just right all the time :grin:

**Comment by thatguyfrombb** [comment] 2021-11-11 20:29
@Richard-L While you still remember, could you tell us in which level and area the pickup in the screenshot is? Both testing and developing a fix is much easier when we know exactly what to look at/for :)

**Comment by Richard-L** [comment] 2021-11-11 20:49
Absolutely, this was in the room of (I think) the last secret of Atlantis, where you have to rush up the slope against Atlanteans before the timed door closes.

I also has another occurrence in the first TRUB level yesterday I could illustrate if needed.

**Comment by thatguyfrombb** [comment] 2021-11-11 21:19
> I also has another occurrence in the first TRUB level yesterday I could illustrate if needed.

Thanks! It'd be great if you could do that, in case the issue is different somehow.

**Comment by rr-** [comment] 2021-11-11 22:10
Forgot to mention, it was fixed in 35afe7cd.

**Closed by rr-** 2021-11-11 22:10 UTC
Labels: T1M bug
